package com.apunto.copytarget;

public enum DecisionCode {
    TARGET_CALCULATED,
    EXECUTED,
    PARTIALLY_FILLED,
    RECONCILED_AFTER_TIMEOUT,

    SKIPPED_BELOW_MIN_NOTIONAL,
    SKIPPED_BELOW_MIN_QTY,
    SKIPPED_ROUNDED_TO_ZERO,
    SKIPPED_CAPITAL_EXHAUSTED,
    SKIPPED_SYMBOL_NOT_SUPPORTED,
    SKIPPED_NO_BINANCE_ALIAS,
    SKIPPED_USER_POSITION_LIMIT,
    SKIPPED_NOT_SELECTED_BY_USER_POLICY,
    SKIPPED_DELTA_TOO_SMALL,
    SKIPPED_ALREADY_AT_TARGET,

    BLOCKED_SOURCE_EQUITY_MISSING,
    BLOCKED_SOURCE_EQUITY_STALE,
    BLOCKED_SOURCE_EQUITY_INVALID,
    BLOCKED_SOURCE_SNAPSHOT_MISMATCH,
    BLOCKED_SOURCE_EVENT_STALE,
    BLOCKED_LEVERAGE_LIMIT,
    BLOCKED_MARGIN_MODE_MISMATCH,
    BLOCKED_INSUFFICIENT_MARGIN,
    BLOCKED_IDEMPOTENCY_PAYLOAD_CONFLICT,
    BLOCKED_BUDGET_RESERVATION_FAILED,
    BLOCKED_EXISTING_EXPOSURE_CONFLICT,
    BLOCKED_TARGET_SYMBOL_COLLISION,
    BLOCKED_TARGET_POSITION_SNAPSHOT_UNAVAILABLE,
    BLOCKED_TARGET_POSITION_SNAPSHOT_STALE,

    REJECTED_BY_BINANCE_FILTER,
    REJECTED_BY_BINANCE_BALANCE,
    REJECTED_BY_BINANCE_LEVERAGE,
    REJECTED_BY_BINANCE_MARGIN_MODE,
    REJECTED_BY_BINANCE_UNKNOWN,

    EXECUTION_TIMEOUT_RECONCILING,
    EXECUTION_AMBIGUOUS_RECONCILING
}
